import { createApp } from 'vue';
import Toast from 'primevue/toast';
import ToastService from 'primevue/toastservice';
import PrimeVue from 'primevue/config';
import App from './App';
import 'primeflex/primeflex.css';
import 'primevue/resources/themes/saga-blue/theme.css';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';
import interceptor from './api/interceptors';
import './registerServiceWorker';
import router from './router';
import store from './store';

interceptor();
const app = createApp(App);
app.use(store);
app.use(router);
app.use(PrimeVue);
app.use(ToastService);
app.component('Toast', Toast);
app.mount('#app');
